group_vars: restructure packagelist and add utils
Freifunk-Spalter/bbb-configs pull request #51
Opened 2021-07-29 12:33 UTC by Akira25

Fixes #47.

2021-08-04 13:18 UTC, spolack requested changes
Thank you - i left some remarks.

Please also check, if that resulting image fits on devices with only 8MB of flash. e.g. by  `ansible-playbook play.yml --limit emma-oso-2ghz --tags image`

2021-08-04 13:18 UTC, spolack commented on group_vars/role_corerouter/imageprofile.yml
>    - snmp-mibs
This can be dropped IMHO, as we dont use it

2021-08-04 13:18 UTC, spolack commented on group_vars/role_corerouter/imageprofile.yml
> +  - ip
Do you mean ip-full, which is also included fore role_uplink_gateway?

Perhaps it should be shipped via group_vars/all/..

.. If so, then please remove it from role_uplink_gateways list.

2021-08-04 13:18 UTC, spolack commented on group_vars/role_corerouter/imageprofile.yml
> +  - tcpdump-mini
already being included at
https://github.com/Freifunk-Spalter/bbb-configs/blob/master/group_vars/all/imageprofile.yml

2021-08-04 13:18 UTC, spolack commented on group_vars/role_corerouter/imageprofile.yml
> +  - mtr
already being included at
https://github.com/Freifunk-Spalter/bbb-configs/blob/master/group_vars/all/imageprofile.yml

2021-08-04 13:18 UTC, spolack commented on group_vars/role_corerouter/imageprofile.yml
> +  - iperf3
already being included at
https://github.com/Freifunk-Spalter/bbb-configs/blob/master/group_vars/all/imageprofile.yml

2021-08-04 13:18 UTC, spolack commented on group_vars/role_corerouter/imageprofile.yml
> +  - vnstat
already being included at
https://github.com/Freifunk-Spalter/bbb-configs/blob/master/group_vars/all/imageprofile.yml

2021-08-04 13:18 UTC, spolack commented on group_vars/role_corerouter/imageprofile.yml
> +  - iwinfo
Is that necessary? iw is by far more powerful, except the fact one has to learn the syntax.

Perhaps it should be shipped via group_vars/all/..
https://github.com/Freifunk-Spalter/bbb-configs/blob/master/group_vars/all/imageprofile.yml

2021-08-04 13:18 UTC, spolack commented on group_vars/role_uplink_gateway/imageprofile.yml
> +  - tcpdump-mini
See comments above.

2021-11-08 23:46 UTC, Akira25 commented
I haven't worked on this for a long time. For a clean list of PRs, I will close this.

2021-11-08 23:46 UTC, closed without merging