philmel: cleanup
Freifunk-Spalter/bbb-configs pull request #893
Opened 2024-07-16 10:29 UTC by FFHener

I had a meeting with @patrella and we definied together how the location will look like after the maintenance work.

Please review, but do not merge as it doenst reflect the current state. I will merge it after the on site work is done

2024-07-30 08:03 UTC, noxilixon reviewed
:+1:

2024-07-30 08:27 UTC, booo commented on locations/philmel.yml
> +  # TODO: For the peer GSBS2 802.11s is not working
It is not that 802.11s is not working but it's only working on indoor channels or none-DFS channels with reduced output power. Therefore we need outdoor AP mode SSIDs for all towers if we deploy OpenWRT devices.

Setting up a tower with multiple nodes in 802.11s on the same channel is also a bad idea. We should follow a concept similar to the UBNT APs with the OpenWRT APs.

2024-07-30 12:55 UTC, booo commented on locations/philmel.yml
> +  # TODO: For the peer GSBS2 802.11s is not working
As far as I remember.

The indoor channels are for indoor use and the indoor channels are quite crowded too.

2024-11-18 10:24 UTC, noxilixon requested changes

2024-11-18 10:24 UTC, noxilixon commented on locations/philmel.yml
> +  # TODO: Change on all devices (mgmt vlan)
I am really not a fan of todo comments in a pr. Just make a issue for that.

2024-11-18 10:24 UTC, noxilixon commented on locations/philmel.yml
> +# TODO:give back old IP
Please resolve this, or create an extra issue and delete the todo comment.

2024-11-18 10:24 UTC, noxilixon commented on locations/philmel.yml
> +    prefix: 10.230.2.32/28
These ips were already used for meshing. This should match the range in comment Line 108.

2024-12-01 11:52 UTC, noxilixon approved these changes

2024-12-06 17:24 UTC, Noki commented
the idea with the custom wireless profile for AP meshing did not work, we should revert it and merge and simply help the guy to upgrade the router to using 802.11s.

2024-12-16 13:48 UTC, merged